[package]
name = "rmqtt-acl"
version = "0.1.1"
authors = ["rmqtt-rs <rmqttd@126.com>"]
edition = "2021"

[dependencies]
rmqtt = "0.1"
log = "0.4.14"
serde = { version = "1.0.126", features = ["derive"] }
ahash = "0.7.2"
dashmap = "4.0.2"