[package]
name = "rmqtt-cluster-raft"
version = "0.1.1"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2021"

[dependencies]
rmqtt = "0.2"
rmqtt-raft = { git = "https://github.com/rmqtt/rmqtt-raft", tag = "0.1.3" }
#rmqtt-raft = { path = "../../../rmqtt-raft" }
log = "0.4"
async-trait = "0.1.36"
serde = "1.0.104"
serde_json = "1.0.48"
parking_lot = "0.10.0"
tokio = "1.10"
futures = "0.3.15"
once_cell = "1.4.1"
anyhow = "1"
ahash = "0.7.2"
bincode = "1.3.3"
dashmap = "4.0.2"
chrono = "0.4.19"
lazy_static = "1.4.0"
backoff = { version = "0.4", features = ["futures", "tokio"] }