[workspace]
members = [
  "rmqtt",
  "rmqtt-plugins/rmqtt-plugin-template",
  "rmqtt-plugins/rmqtt-web-hook",
  "rmqtt-plugins/rmqtt-auth-http",
  "rmqtt-bin",
]

[patch.crates-io]
rmqtt = { path = "rmqtt" }
