
[target.x86_64-unknown-linux-musl]
image = "rustembedded/cross:x86_64-unknown-linux-musl-0.1.16"

[target.i686-unknown-linux-musl]
image = "rustembedded/cross:i686-unknown-linux-musl-0.1.16"

[target.aarch64-unknown-linux-musl]
image = "rustembedded/cross:aarch64-unknown-linux-musl-0.1.16"

