[package]
name = "rmqtt-plugin-template"
version = "0.1.1"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2018"

[dependencies]
rmqtt = { git = "https://github.com/rmqtt-rs/rmqtt.git", version="0.1.3"}
#rmqtt = { path = "../../rmqtt" }
log = "0.4"
async-trait = "0.1.36"
tokio = "1.5"
bytestring = "1.0"