[package]
name = "rmqtt-plugin-template"
version = "0.1.1"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2018"

[dependencies]
rmqtt = { git = "https://github.com/rmqtt-rs/rmqtt.git", tag = "v0.1.0"}
log = "0.4"
async-trait = "0.1.36"

