##--------------------------------------------------------------------
## rmqtt-acl
##--------------------------------------------------------------------

#Disconnect if publishing is rejected
disconnect_if_pub_rejected = true

rules = [
    ["allow", { user = "dashboard" }, "subscribe", ["$SYS/#"]],
    ["allow", { ipaddr = "127.0.0.1" }, "all", ["$SYS/#", "#"]],
    ["deny", "all", "subscribe", ["$SYS/#", { eq = "#" }]],
    ["allow", "all"]
]

