[package]
name = "rmqtt-stats"
version = "0.1.0"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmqtt = "0.2"
log = "0.4"