[package]
name = "rmqtt-web-hook"
version = "0.1.1"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2018"

[dependencies]
rmqtt = { git = "https://github.com/rmqtt-rs/rmqtt.git", version="0.1.3"}
#rmqtt = { path = "../../rmqtt" }
futures = "0.3.13"
log = "0.4"
async-trait = "0.1.36"
serde = { version = "1.0.104", features = ["derive"] }
reqwest = { version = "0.11.3", features = ["json"] }
parking_lot="0.10.0"
serde_json = "1.0.48"
crossbeam = "0.8"
tokio = { version = "1.4", default-features=false}
lazy_static = "1.4"
base64 = "0.12.0"
chrono = "0.4.19"