[package]
name = "rmqtt"
version = "0.1.6"
authors = ["rmqtt <rmqttd@126.com>"]
description = "MQTT Server for v3.1 and v3.1.1 protocols"
repository = "https://github.com/rmqtt-rs/rmqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT"
exclude = [".gitignore", ".cargo/config"]
edition = "2018"

[lib]
name = "rmqtt"
path = "src/lib.rs"

[dependencies]
ntex = { version = "0.3.16", features = ["rustls"] }
ntex-mqtt = { git = "https://github.com/rmqtt-rs/ntex-mqtt", version = "0.6.8"}
#ntex-mqtt = { path = "../../ntex-mqtt" }
futures = "0.3.15"
tokio = { version = "1.6.0", features = ["full"] }
tonic = "0.4.3"
prost = "0.7.0"
once_cell="1.7.2"
dashmap = "4.0.2"
ahash = "0.7.2"
bytes = {version = "1.0.1", features = ["serde"]}
bytestring = {version = "1.0.0", features = ["serde"]}
thiserror = "1.0.24"
anyhow = "1.0.40"
lazy_static="1.4.0"
async-trait = "0.1.50"
parking_lot="0.11.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
chrono = "0.4.19"
uuid = { version = "0.8.2", features = ["v4"] }
rand = "0.8.3"
crossbeam = "0.8.0"
governor = "0.3.2"
config = "0.11.0"
leaky-bucket = "0.10.0"
linked-hash-map = "0.5.4"
log = "0.4.14"
slog = "2.7.0"
slog-async = "2.6.0"
slog-logfmt = "0.1.0"
env_logger = "0.8.3"
base64 = "0.13.0"
bincode = "1.3.3"

[build-dependencies]
tonic-build = "0.4.2"
