[package]
name = "rmqtt"
version = "0.1.3"
authors = ["rmqtt <rmqttd@126.com>"]
description = "MQTT Server for v3.1 and v3.1.1 protocols"
repository = "https://github.com/rmqtt-rs/rmqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT"
exclude = [".gitignore", ".cargo/config"]
edition = "2018"

[lib]
name = "rmqtt"
path = "src/lib.rs"

[dependencies]
ntex = "0.3"
ntex-mqtt = { git = "https://github.com/rmqtt-rs/ntex-mqtt", version = "0.6.8"}
futures = "0.3.13"
tokio = { version = "1.4", features = ["full"] }
rustls = "0.19"
tokio-rustls = "0.22"
tonic = "0.4.3"
prost = "0.7.0"
url = "1.0"
once_cell="1.4.1"
dashmap = "3.11"
ahash = "0.7.2"
bytes = {version = "1", features = ["serde"]}
bytestring = {version = "1", features = ["serde"]}
thiserror = "1"
anyhow = "1"
lazy_static="1.4"
async-trait = "0.1.36"
parking_lot="0.11"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
chrono = "0.4.19"
uuid = { version = "0.8.1", features = ["v4"] }
rand = "0.8"
crossbeam = "0.8"
governor = "0.3"
config = "0.11"
regex = "1"
leaky-bucket = "0.10"
linked-hash-map = "0.5.3"
log = "0.4"
slog = "2.7"
slog-async = "2.6"
slog-logfmt = "0.1"
env_logger = "0.8"
base64 = "0.13"
bincode = "1.2.1"
tower = "0.4.7"

[build-dependencies]
tonic-build = "0.4.2"