[package]
name = "rmqttd"
version = "0.1.8"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "rmqttd"
path = "src/server.rs"

[profile.dev]
opt-level = 0

[profile.release]
lto = true
opt-level = 's'
codegen-units = 1


[dependencies]
rustls = "0.19"
anyhow = "1.0.40"
warp = "0.3.1"

##mqtt broker
rmqtt = "0.1"
##plugins
rmqtt-acl = "0.1"
rmqtt-web-hook = "0.1"
rmqtt-auth-http = "0.1"
rmqtt-cluster-broadcast = "0.1"
rmqtt-plugin-template = "0.1"

[package.metadata.plugins]
rmqtt-acl = {default_startup = true}
rmqtt-web-hook = {}
rmqtt-auth-http = {}
rmqtt-cluster-broadcast = {}
rmqtt-plugin-template = {}

[build-dependencies]
toml = "0.5"
chrono = "0.4.15"

