[package]
name = "rmqttd"
version = "0.1.7"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "rmqttd"
path = "src/server.rs"

[profile.dev]
opt-level = 0

[profile.release]
lto = true
opt-level = 's'
codegen-units = 1


[dependencies]
rustls = "0.19"
anyhow = "1.0.40"
warp = "0.3.1"

##plugins-release
rmqtt = { git = "https://github.com/rmqtt-rs/rmqtt.git", version="0.1.7"}
rmqtt-acl = { git = "https://github.com/rmqtt-rs/rmqtt.git", version="0.1.1"}
rmqtt-web-hook = { git = "https://github.com/rmqtt-rs/rmqtt.git", version="0.1.1"}
rmqtt-auth-http = { git = "https://github.com/rmqtt-rs/rmqtt.git", version="0.1.1"}
rmqtt-cluster-broadcast = { git = "https://github.com/rmqtt-rs/rmqtt.git", version="0.1.1"}
#rmqtt-plugin-template = { git = "https://github.com/rmqtt-rs/rmqtt.git", version="0.1.1"}

##plugins-dev
#rmqtt = { path = "../rmqtt" }
#rmqtt-acl = { path = "../rmqtt-plugins/rmqtt-acl" }
#rmqtt-web-hook = { path = "../rmqtt-plugins/rmqtt-web-hook" }
#rmqtt-auth-http = { path = "../rmqtt-plugins/rmqtt-auth-http" }
#rmqtt-cluster-broadcast = { path = "../rmqtt-plugins/rmqtt-cluster-broadcast" }
#rmqtt-plugin-template = { path = "../rmqtt-plugins/rmqtt-plugin-template" }

[package.metadata.plugins]
rmqtt-acl = {default_startup = true}
rmqtt-web-hook = {}
rmqtt-auth-http = {}
rmqtt-cluster-broadcast = {}
#rmqtt-plugin-template = {}

[build-dependencies]
toml = "0.5"
chrono = "0.4.15"

